name: Deploy to Production

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Run lint
        run: npm install

      - name: Build Docker image
        run: docker build . -t willebergh/mega-dashboard:production --build-arg REACT_APP_HOST_API=https://api.twostack-system.se

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: docker push willebergh/mega-dashboard:production

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Update Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TSS_PROD_HOST }}
          username: ${{ secrets.TSS_PROD_USERNAME }}
          password: ${{ secrets.TSS_PROD_PASSWORD }}
          script: ~/mega/update_dashboard.sh
